version: '3.8'

services:
  node_backend:
    container_name: express_proxy
    image: express_proxy:0.0.1
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - EXTERNAL_PORT=3000
      - PGDATABASE=db_spotter_prod
      - PGUSER=db_owner
      - PGPASSWORD=toor
      - PGHOST=node_db
      - MICR_API=34.196.99.153:5000/api/
    depends_on:
      - node_db
  node_db:
    container_name: node_db
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=db_owner
      - POSTGRES_PASSWORD=toor
      - POSTGRES_DB=db_spotter_prod
    volumes:
      - nps_data:/var/lib/postgresql/data

volumes:
  nps_data: {}

